### ISSUE TITLE
TO-DO : Tasks Status Manage ， control status ,  restart .

### ISSUE THREAD

**Issue by lijiang2014** [lijiang2014/thht#5]
管理节点 记录作业的状态并缓存，方便查询。
作业重算的处理。

- [x] 在数据库中保存状态列表
- [x] 能够对状态/作业进行检索 (作业运行中) , 计数功能。
- [x] 能够对状态/作业进行检索 (作业完成后), 计数功能。
- [x] 重算时能自动排除已经完成的检索

**Comment by lijiang2014** [comment]
队列中的作业可以从 redis 中获取 ， 但已经完成的并没有进行管理 。
需要进行 redis - FS 的二级缓存。
input Job List || -> Down Job List <S/F> || -> Push Job List . -> new input Job List 
但如何对JOB 进行标识是一个问题。

**Comment by arafortune** [comment]
kill 功能。 manager 接收到 请求后，保存数据库并退出环境。

**Comment by lijiang2014** [comment]
-[x] 在数据库中保存状态列表
-[ ] 能够对状态/作业进行检索 (作业运行中)
-[ ] 能够对状态/作业进行检索 (作业完成后)
-[ ] 重算时能自动排除已经完成的检索
